### ISSUE TITLE
Aggregate processes from different servers client-side

### ISSUE THREAD

**Issue by huard** [bird-house/birdy#101]
## Description

Support 
```wps = WPSClient(<list of WPS servers>)```

**Comment by huard** [comment]
## Design considerations
There are two potential use cases: 
1. Aggregate different processes from different birds
2. Aggregate the same processes for the same bird running on different servers

I think there is little value in 1, as users can simply instantiate different objects. We should thus focus on 2, where birdy would play the role of a rudimentary load balancer, sending computations to the server providing the result in the shortest time. 

Enforce the different servers are running the same version of the wps server. 

When calling the describe process request, check which server responds fastest, and select this server as the default target.

**Comment by cehbrecht** [comment]
@huard Why not use a load-balancer in front of the wps services? One could use nginx:
https://nginx.org/en/docs/http/load_balancing.html 

... or adding these more specific WPS checks to a middleware like twitcher? There are more WPS clients which would like to use this load-balancing feature.

**Comment by tomLandry** [comment]
Also, I see "_sending computations to the server providing the result in the shortest time_". This is pretty close to the type of responsibility that Weaver should have. Get the request from the user once, then manage it transparently based on various factors (cost, execution speed, type of algorithm, delays, etc.)

**Comment by huard** [comment]
These are all server-side. I think it would be useful to have basic client-side functionality. This PR might not be it, however, so happy to have feedback. 

Let me put it this way: can I, as a user, dynamically register services on weaver, then let it handle my requests ? If yes, then let's write a birdy interface to weaver.

**Comment by fmigneault** [comment]
@huard 
Yes, you can deploy a WPS service using an URL reference in the body, and it should loop through every found WPS1 process to generate WPS-REST variants locally. These can after be called with the WPS-3-REST interface, and will convert/dispatch the process execution call to the original service.

**Comment by tomLandry** [comment]
What Francis describes is pretty much was is deployed for climatedata.ca (now live!), where Finch is registered and exposed as WPS RESTful, to be used by the portal. So in a sense... it's released.

**Comment by fmigneault** [comment]
Repo:
https://github.com/crim-ca/weaver

Docker images can already be built, but automated builds is still in the pipeline (when I will get spare time).

**Comment by tomLandry** [comment]
The deployment, including Finch, is exposed through pavics.climatedata.ca (might be unreachable for security reasons). If pavics.ouranos.ca needs to connect to it, I see no problems.

**Comment by huard** [comment]
Closing, as it seems the solution sits outside birdy.
