### ISSUE TITLE
Support ESGF CWT API extension

### ISSUE THREAD

**Issue by huard** [bird-house/birdy#102]
## Description

WPSClient does not support the owslib esgfapi objects.

**Comment by tomLandry** [comment]
Let's keep this issue alive. This ideally needs to be documented in the OGC engineering report for our Testbed-14 extension for DOE.

**Comment by huard** [comment]
So for your info Carsten has a branch in owslib to support the extension and a notebook example. Still needs some work but the basics are working. It's only the `birdy.WPSClient` part that needs to be updated to add support. I won't be able to spend time on this until a few weeks.

**Comment by tomLandry** [comment]
Ok, so tagging @davidcaron on this one. It's helping for PAVICS-Hydro too, right?

**Comment by huard** [comment]
There are no immediate plans to support the ESGF-API extension in the proposal, but this is something that could be contributed as part of the maintenance and improvements.  
@davidcaron The first step would be to review the [API document](https://github.com/ESGF/esgf-compute-api/blob/master/docs/source/cwt.compat.rst)
Then review the esgfapi branch of owslib (it's a first pass). 
Then add support for those objects in birdy.

**Comment by huard** [comment]
branch fix-102 fixes some issues with non-python ids.
Adding tests for ESGF-API objects.

**Comment by huard** [comment]
Next step would be to repeat https://github.com/bird-house/OWSLib/blob/esgfwps/examples/notebooks/owslib-aims-llnl-demo.ipynb with birdy.

**Comment by cehbrecht** [comment]
If we make `owslib.esgfapi` an optional dependency we could merge branch fix-102 to master ... when ready.

**Comment by huard** [comment]
@cehbrecht It's not great though to rely on an owslib branch. Do you think the owslib folks would agree to a directory of "extensions" ? 
E.g. `owslib.wps.ext.esgf` or `owslib.ext.wpsesgf` ?

**Comment by cehbrecht** [comment]
I can't say if owslib people will accept. The ESGF-API is not a standard. Technically we could start an owslib esgf-api extension on birdhouse which could be optionally installed . We would avoid the insallation issue (relying on a branch) and we get some more time to tune the ESGF-API before it goes into owslib.

**Comment by huard** [comment]
Sounds good.

**Comment by huard** [comment]
Ok, I'll put in some time to write the aggregate process.
