### ISSUE TITLE
High-level THREDDS user interface

### ISSUE THREAD

**Issue by huard** [bird-house/birdy#104]
## Description

I'd like to have a high-level user interface to data stored on THREDDS that would play well with our WPSClient. 

Not clear yet to me what this interface should look like.

**Comment by cehbrecht** [comment]
@huard You don't mean siphon?
https://github.com/Unidata/siphon

**Comment by huard** [comment]
I think it's an excellent starting point, but I'd like to make it easier for users to create custom ensembles.

**Comment by huard** [comment]
This is probably not the right place for this. Closing.
