### ISSUE TITLE
Required inputs should show as positional arguments in native client

### ISSUE THREAD

**Issue by huard** [bird-house/birdy#120]
## Description

Processes with required inputs show up as keyword arguments with default value set to None, instead of as positional arguments.

**Comment by davidcaron** [comment]
I think this is more a pywps issue, because when we check the DescribeProcess, there is no default value for `lon0`: https://finch.crim.ca/wps?service=WPS&request=describeprocess&identifier=subset_ensemble_BCCAQv2&version=1.0.0

**Comment by davidcaron** [comment]
I think I found it https://github.com/davidcaron/pywps/commit/4e76006d79b6a029a959e106c529a956d4e79b63

I'll test it and submit a PR.

**Comment by davidcaron** [comment]
Ah, I see I just understood that your issue was about the `rcp` and `variable` parameters in the `subset_ensemble_BCCAQv2` process, not the `lon0` input. I think this should be changed also, but it's not what you meant. Sorry for the spam.

**Comment by huard** [comment]
Correct. I think it's a small fix in the FunctionBuilder call.
