### ISSUE TITLE
function signature is confused by default and min_occurs mismatch

### ISSUE THREAD

**Issue by huard** [bird-house/birdy#133]
## Description

Not sure if this is a bug, but when a process has inputs with min_occurs=1 followed by processes with min_occurs but with a default value (which is strange but allowed), the python signature assigns wrong defaults to these arguments. This can be fixed by making sure that inputs with default arguments have min_occurs=0.

**Comment by Zeitsperre** [comment]
Ah, that explains your recent changes on my PRs. I was wondering about them...
