### ISSUE TITLE
Retrieve the data if no converter is found

### ISSUE THREAD

**Issue by huard** [bird-house/birdy#136]
## Description

At the moment, if no converter is available, `get(asobj=True)` returns the link. I suggest that instead we return the output of `retrieveData()`.

**Comment by huard** [comment]
@cehbrecht Are you ok with this ?

**Comment by cehbrecht** [comment]
@huard this is probably what you expect. Could this be the behavior of a "default" converter when no other is available?

**Comment by huard** [comment]
Sure, see #137
