### ISSUE TITLE
Update Birdhouse-Birdy on PyPI

### ISSUE THREAD

**Issue by Zeitsperre** [bird-house/birdy#156]
As of this date, the latest version of Birdy available on PyPI is [0.6.2](https://pypi.org/project/birdhouse-birdy/). This is a reminder that we need to push changes to both conda-forge and PyPI when we release a Birdy.

## Environment

* Birdy version used, if any: 0.6.5
* Python version, if any: 3.x
* Operating System: All

**Comment by huard** [comment]
@cehbrecht Could you give @Zeitsperre permission to make pypi releases ?
This is blocking a demo for a class.

**Comment by huard** [comment]
```
Collecting birdhouse-birdy
  Using cached birdhouse-birdy-0.6.2.tar.gz (23 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/david/.conda/envs/btest/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-etafvwjc/birdhouse-birdy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-etafvwjc/birdhouse-birdy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-etafvwjc/birdhouse-birdy/pip-egg-info
         cwd: /tmp/pip-install-etafvwjc/birdhouse-birdy/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-etafvwjc/birdhouse-birdy/setup.py", line 12, in <module>
        requires = [line.strip() for line in open('requirements.txt')]
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by davidcaron** [comment]
I think this should fix pypi releases: https://github.com/bird-house/birdy/pull/166

**Comment by cehbrecht** [comment]
@Zeitsperre can you give me your username on pypi? I can add you as collaborator:
https://pypi.org/manage/project/birdhouse-birdy/collaboration/

**Comment by cehbrecht** [comment]
@Zeitsperre @huard Should I make a new release and push it to pypi?

**Comment by huard** [comment]
@cehbrecht Yes please.

**Comment by cehbrecht** [comment]
@huard released on pypi:
https://pypi.org/project/birdhouse-birdy/0.6.6/

... probably need to wait for conda-forge build.

**Comment by huard** [comment]
Thanks ! Much appreciated.
