### ISSUE TITLE
Request mime type data format for outputs

### ISSUE THREAD

**Issue by huard** [bird-house/birdy#163]
## Description

Some ComplexData outputs can support multiple data formats (e.g. NetCDF and opendap). WPS allows requests to embed the type of output data format requested. 

Birdy should have a mechanism to specify the data format of expected outputs when calling the process. 

One option is to add additional inputs to the function, for example <output_identifier>_type, that could be set with the desired mimetype of the output.

**Comment by huard** [comment]
@cehbrecht @davidcaron Ideas ? Suggestions ?

**Comment by davidcaron** [comment]
So do you suggest that this specified output format be sent to the server as information on how to output the data? If so, as far as I know, Pywps doesn't support any 'standard' way to ask for an output format when executing a Process?

I've found some mentions of the "AcceptFormats" parameter in some OGC Specs (WPS 1, 2 WFS, etc.) I've only seen it used with GetCapabilities, so I'm not sure if the intention was to use it with the Execute request. 

In OGC API, they require the support of HTTP content-negotiation (the 'Accept' header) http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#encodings At the bottom of this section, they suggest solutions for embedding the output format in the url (`accept` or `f` parameters).

But do you simply suggest keeping the specified output format inside birdy, only to simplify parsing the list of outputs after the process is done?

**Comment by huard** [comment]
It seems to be supported in OWSlib: https://github.com/geopython/OWSLib/blob/5f9751c7b1c9108b967270dfbb7a41bf7068999a/owslib/wps.py#L772

The ResponseDocument includes a wps:Output section in which requests can specify the mime type of the output. I think this is fed into pywps Output objects `data_format` attribute.

**Comment by huard** [comment]
http://geoprocessing.info/wpsdoc/1x0ExecuteGETOutputs

**Comment by cehbrecht** [comment]
@huard you mean that can ask a single output parameter to return a different result (url) depending on the requested mimetype? This is currently not the case for pywps. I'm not sure if this is intended by the wps protocol ... didn't check yet. 

It would mean that the output url is different depending on the mime type ... but I think we can only return one output url.

**Comment by huard** [comment]
@cehbrecht Yes. 

I think it's the responsibility of the process to embed that logic. Something like: 
```
if response.outputs['out'].data_type == "...":
  ...
else : 
  ...
```

**Comment by davidcaron** [comment]
@huard I understand what you mean now, I think it makes sense and follows the specification. As for the implementation... I think your suggestion (`<output_identifier>_type`) makes sense.

One situation where this would look a bit weird is if we have a lot of outputs. 

Apart from grouping the output parameters in a single argument `{"output_identifier": "mimetype", "output2": "mimetype"}` Which I'm not sure I would prefer or not, I don't have any other suggestion.

**Comment by huard** [comment]
@cehbrecht Another API would be to use the output identifier in the call arguments, but instead of passing an input value, you pass the output mimetype, e.g.
`wps.process(input1=10, output1='application/x-netcdf')`
This would fail however if an output identifier was identical to an input identifier, which the standard probably allows. 
Otherwise, I think I'd go along with the dictionary argument, but again, whatever name we choose will potentially shadow an input identifier.
