### ISSUE TITLE
Remove direct Ipython import

### ISSUE THREAD

**Issue by Zeitsperre** [bird-house/birdy#205]
@cehbrecht 

Due to additions made [here](https://github.com/bird-house/birdy/commit/2bea46c1aa20a91dfe38741476e202919c4b1ffa), `Ipython` is now a firm installation dependency. This needs to be dealt with before the next release of `Birdy` (post-0.8.0).

**Comment by Zeitsperre** [comment]
Context: https://github.com/conda-forge/birdy-feedstock/pull/7

**Comment by huard** [comment]
The import should be in a try statement. My mistake.
