### ISSUE TITLE
Connect to Zenodo

### ISSUE THREAD

**Issue by huard** [bird-house/birdy#215]
## Description

I think it would be useful if all components of the birdhouse stack were registered on Zenodo, possibly under a "birdhouse" community.

**Comment by huard** [comment]
@cehbrecht,  @nilshempelmann  Do you want to administer a birdhouse zenodo community where all components could be tied together?

**Comment by Zeitsperre** [comment]
@huard You and/or I could also help with the administration/maintenance of the community, but I think only one user can have curation/administration duties for the community. I'm not even sure if ownership can be easily transferred? It feels like a very new feature.

**Comment by huard** [comment]
I created a birdhouse community on Zenodo. Hoping the maintenance can eventually be shared with others.
