### ISSUE TITLE
Wordcounter does not work

### ISSUE THREAD

**Issue by huard** [bird-house/birdy#34]
## Description
Calling `wordcounter` process from birdy launches the progress bar, goes to 100% but then nothing seems to happen. 

## Environment

* Birdy version used, if any: master
* Python version, if any: 2
* Operating System: ubuntu

## Steps to Reproduce

```
birdy wordcounter --text http://www.gutenberg.org/cache/epub/19033/pg19033.txt
```

**Comment by cehbrecht** [comment]
It is not Birdys fault:
```
$ export WPS_SERVICE=https://mouflon.dkrz.de/ows/proxy/emu
$ birdy wordcounter --text http://bird-house.github.io/
ProcessSucceeded  [------------------------------------]    2%  0d 00:01:43
Output:
output=https://mouflon.dkrz.de:8090/wpsoutputs/emu/4f351728-7096-11e8-8f74-868dacf6ed58/out_o5Gcs7.txt
```

It seems to be a bug in pywps on Python 3.x. Force the Emu installation to use Python 2.7 and the wordcounter should work with birdy.

I need to investigate in pywps what is going wrong on Python 3.

**Comment by huard** [comment]
Ah sorry, I thought I was in python2.
