### ISSUE TITLE
show status log in native client

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/birdy#39]
## Description

Currently we just wait until the process is done without getting feedback. It could display a progress bar (like already used for the command line), something that plays nicely with jupyter-lab (widgets). Status display should be optional ... if used by other scripts you don't want these outputs.

**Comment by huard** [comment]
Started thinking about this... 
Would that mean that we'd call process asynchronously, then poll the status repeatedly to get the progress update, and display it ?
@davidcaron Is this something you'd like to work on ? 
@tomLandry I think a demo of a progress bar at ESGF would steal the show. 

```
$ pip install ipywidgets
$ jupyter labextension install @jupyter-widgets/jupyterlab-manager

import ipywidgets as widgets
widgets.FloatProgress(
    value=7.5,
    min=0,
    max=10.0,
    step=0.1,
    description='Loading:',
    bar_style='info',
    orientation='horizontal'
)

```

**Comment by tomLandry** [comment]
@huard , until Christmas, @davidcaron is working part-time on Birdy and should support recent security advances in Twitcher and Magpie for PAVICS-Hydro - that also includes Jupyter. Please see with him in your next meeting to organize his priorities, I will then approve them.

**Comment by davidcaron** [comment]
Sure, I'm interested, depending on priorities. When is the ESGF?

**Comment by cehbrecht** [comment]
OWSLib supports calling WPS in async mode ... we *just* need to provide the right user interface ;) A `cancel` button would be nice :) On server side this is only supported with WPS 2.0.0. For WPS 1.0.0 it would just stop the client polling.

**Comment by huard** [comment]
But "dismiss" does not seem to be implemented in OWSLib...

**Comment by huard** [comment]
And I don't think pywps supports "dismiss" either...

**Comment by cehbrecht** [comment]
... WPS 2.0 implementation is missing in OWSLib. But having a `cancel` button would be a start and *motivation* ... currently it would just stop polling the WPS service.

**Comment by cehbrecht** [comment]
@huard I have tried the `progress_widget`. Looks nice :) It might also display a status message and change the color with process state. It could be an `IntSlider` ... I think only `int` values are allowed in WPS progess. 

The `pywidgets` should be an optional dependencies.

**Comment by tomLandry** [comment]
Fyi, our upcoming version of Twitcher is WPS 2.0

**Comment by huard** [comment]
The color already turns to green when the process is completed and orange I think when it fails.
Ok for intslider.
OK

**Comment by tomLandry** [comment]
David H, is it too late to add David C as an author on Birdy? For AGU or ESGF... Personally I will definitely facilitate the work being done, and even possibly presenting it, but David C will directly contribute to the code base.

**Comment by huard** [comment]
For AGU, I think it's too late. No problem for ESGF.

**Comment by cehbrecht** [comment]
@huard I would take some of your code from the `progress_widget` branch and add *async* call monitoring. The  monitor can use python logging, so we get a progress log in a log-file.

Adding the nice jupyter widget can be added in a next step ... having something for the demo.
