### ISSUE TITLE
does not handle optional inputs

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/birdy#41]
## Description

Birdy command-line does not recognize that some inputs are optional. It shows an error when inputs are missing.

**Comment by nkadygrov** [comment]
Could you give an example, please?
I don't have such an error.

**Comment by cehbrecht** [comment]
@nkadygrov I just stumbled over it when trying the `ncmeta` process of the latest Emu (master). This process has two optional inputs `dataset` and `dataset_opendap` ... but birdy command-line always wants both inputs.

**Comment by cehbrecht** [comment]
default value was set to `None` and send when option was skipped. We don't need to send options with defaults ... they will be set on the server side. We can add them to the help message.
