### ISSUE TITLE
birdy native client fails for emu "hello" process

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/birdy#45]
## Description

When using the birdy native client to execute the emu "hello" process it fails with the following exception:

```
tests/test_native.py:9 (test_birdmod)
Traceback (most recent call last):
  File "/home/david/src/birdy/tests/test_native.py", line 13, in test_birdmod
    assert m.hello('david') == 'Hello david'
  File "/home/david/src/birdy/birdy/native.py", line 350, in wrapper
    out = self.execute(wrapped.__name__, **ba.arguments)
  File "/home/david/src/birdy/birdy/native.py", line 395, in execute
    out.append(self.process_output(o))
  File "/home/david/src/birdy/birdy/native.py", line 412, in process_output
    typ = BirdyCLI.get_param_type(out)
  File "/home/david/src/birdy/birdy/cli/base.py", line 90, in get_param_type
    if 'boolean' in param.dataType:
TypeError: argument of type 'NoneType' is not iterable
```

## Environment

* Birdy version used, if any: 0.4.0
* Python version, if any:
* Operating System:

## Steps to Reproduce

```
$ make testall

OR

from birdy import native_client
emu = native_client('http://localhost:5000/wps')
emu.hello(name='world')
```

## Additional Information

Check the WPS 1.0.0 spec, table 48:
http://www.opengeospatial.org/standards/wps

**Comment by cehbrecht** [comment]
Opened a ticket at pywps:
https://github.com/geopython/pywps/issues/409

**Comment by huard** [comment]
Your suggestion fixes the issue, but then outputs defined as float are assumed to be strings...

**Comment by cehbrecht** [comment]
> Your suggestion fixes the issue, but then outputs defined as float are assumed to be strings...

... that is why we need to fix pywps as well ... `dataType` can only be skipped when it is of type `string`.

**Comment by huard** [comment]
Right, I confused myself. 
So you know, there are other bugs in the birdy test suite.

**Comment by huard** [comment]
Even the describe process seems to have missing dataType information. This is weird, because it's in the template.
