### ISSUE TITLE
use birdhouse solr search to select input files (urls)

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/birdy#5]
... input files are specified with a solr search query ...

**Comment by huard** [comment]
@cehbrecht Is this still relevant ?

**Comment by cehbrecht** [comment]
I also would keep this open as reminder. The idea was to use ESGF search (or maybe others) to automatically fill the input parameters.

Example by Freva (search for completion):
https://freva.met.fu-berlin.de/guides/bug/
