### ISSUE TITLE
A new name for native.client.BirdyClient?

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/birdy#63]
## Description

We already started a discussion in a ticket/PR ... but I have forgotten at which one.

@huard @davidcaron 
How do you feel about renaming our native client?

My proposals:
* `birdy.client.base.WPSClient` and `from birdy import WPSClient`
* `birdy.client.base.Client` and `from birdy import Client`
* `birdy.client.wps.WPS` and `from birdy import WPS`
* `birdy.wps.client.WPS` and `from birdy import WPS`
* ... or a mixture of these.

For our *native* client we use birdy as a Python WPS client library.

I think we can keep the namespace for command-line interface: 
`birdy.cli`

**Comment by huard** [comment]
+1 for your first option.

**Comment by davidcaron** [comment]
Yes, I would go for the first option too

**Comment by cehbrecht** [comment]
fixed by #66.
