### ISSUE TITLE
native client: how to return multiple values?

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/birdy#64]
## Description

In the current *native* client implementation we either return a single value or a list of values. I would find it more descriptive to return a dictionary with: 
```
key=parameter identifier
value=parameter value
```

@huard @davidcaron 
What do you think?

Here a link from a quick google search:
https://stackoverflow.com/questions/354883/how-do-you-return-multiple-values-in-python

**Comment by huard** [comment]
I'm not a fan of the dictionary solution. What about the NamedTuple suggested on stack ?

**Comment by tomLandry** [comment]
There is a somewhat similar discussion at OGC on how to manage multiple outputs for WPS. It's documented as a recommendation in an Engineering Report... I'll identify later. Please tell me if you want investigation at OGC-standard level.

**Comment by huard** [comment]
Yes, I think it would be useful to develop a solution that will work with the OGC standard and slowly move birdhouse processes to that standard.

**Comment by tomLandry** [comment]
Ok, sending the ER to both Carsten and you.

**Comment by cehbrecht** [comment]
accidentally closed due wrong reference.
