### ISSUE TITLE
add "cancel" functionality to native client

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/birdy#65]
## Description

Though it is not supported in our current WPS implementation (`owslib.wps` and `pywps`), we would like to prepare a *cancel* function for the native client. This would at least stop the WPS process polling ... we can't handle the server side yet. 

Later on, we also like to have a jupyter widget with progress, cancel ( and even pause?) button for demo purposes.

@huard @davidcaron 
comments?

## Additional Information

See discussion in ticket #39.

**Comment by tomLandry** [comment]
@davidcaron Please also consider the upcoming WPS 2.0 REST implementations we have at OGC for cancel and pause. As Carsten said, currently its WPS 1.0 in PyWPS and OWSlib. So to plan a bit ahead, let's also think a bit on how these interfaces might be used. This is not urgent for short term implementaton, but a bit of a roadmap would do great for the upcoming comms at ESGF and AGU.
