### ISSUE TITLE
Convert some online tests to offline tests

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/birdy#67]
## Description

Some of the current online tests should be offline tests so they can be run on travis.

We can mock tests with prepared responses by a WPS (Emu).

**Comment by davidcaron** [comment]
How about using something like this? https://github.com/kevin1024/vcrpy

**Comment by cehbrecht** [comment]
@davidcaron Haven't check the `vcrpy` tool but we don't need to check the full API. That would be more an issue for `owslib`. I thought we can make use of `pytest` and `mock` and "transform" some of the "online" tests. Just googled:
https://medium.com/@bfortuner/python-unit-testing-with-pytest-and-mock-197499c4623c

**Comment by davidcaron** [comment]
I'm working on something... What if we add `emu` to `requirements_dev.txt` and call the service directly?

We wouldn't have to launch a wsgi app, and it would be pretty close to the real thing.

What do you think?

**Comment by cehbrecht** [comment]
Hmm, personally I would prefer mock tests ... but maybe ...

In your case it might be possible to just change travis config to install emu and start it as part of the preparation. We could run `make testall` including the online tests on travis.

**Comment by davidcaron** [comment]
@cehbrecht I'll check how much work it is to make a mock emu. I understand your idea, and I wanted to see if we could skip reimplementing the logic in the emu handlers. In most cases it's very simple logic...

**Comment by huard** [comment]
It sounds to me like a lot of work just for testing. I'd prefer we spend effort on integration testing on real-life platforms. Each time we'd change emu, we'd have to change the mockup.

**Comment by davidcaron** [comment]
I had already done some work trying to use `emu` as a dependency and using the handler functions directly. I'll explore both solutions and come back with some examples.
