### ISSUE TITLE
Handle process and argument names that are not valid python variables

### ISSUE THREAD

**Issue by huard** [bird-house/birdy#69]
## Description

Some WPS processes have dots in their names, e.g. `org.n52.Algorithm` and dashes in their input arguments, e.g. `feature-type`. 

At the moment this crashes the method Factory.

**Comment by huard** [comment]
Check for example with this WPS server:  "http://geoprocessing.demo.52north.org:8080/wps/WebProcessingService?service=WPS&version=2.0.0&request=GetCapabilities"

**Comment by cehbrecht** [comment]
... I just to started add util function for this.

**Comment by cehbrecht** [comment]
reopened ... we still have something todo with non-birdhouse wps services. In birdhouse we were nice and used Python friendly identifiers.

**Comment by huard** [comment]
Sorry, I thought your sanitize function fixed that.
