### ISSUE TITLE
Asynchronous behavior

### ISSUE THREAD

**Issue by huard** [bird-house/birdy#84]
## Description

At the moment with interactive, we return an empty namedtuple because the function returns before the remote processed ended. The problem is that if we wait for the thread to complete, it blocks the user interaction with the widget. I've tried to use a Pool.apply_async, but I've got problems with pickling. 

I think we should offer an `async` keyword to WPSClient that if True, returns something like an `AsyncResult` object with a `get` method that would return the namedtuple. 
If async is false, then the function waits for completion and returns the namedtuple. 

If progress is True, we can show the progress bar in both cases.

**Comment by cehbrecht** [comment]
We could raise a question at `ipywidgets` how to make the async stuff with cancel right.

I would work now on a workaround suitable enough for demo.

Introducing a `Result` class would give us more flexibility and separation of concerns. One could get outputs as reference or as object for each request and output. But that is for next steps ...

**Comment by huard** [comment]
Agreed. I suggest we remove the cancel button for now. It's doing nothing anyway.

**Comment by cehbrecht** [comment]
... I would keep `cancel` for the demo.

**Comment by huard** [comment]
I feel it's like false advertising.
