### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by huard** [bird-house/birdy#90]
## Description

Some pywps servers have a lot of processes and it can take a long time for the calls to `describeprocess` to complete. 

Would it be possible to put the describeprocess calls in a parallel queue ? The idea would be to build fake methods from the getcapabilities so that we can return an object rapidly and people can browse the object for processes of interest (the class doc). If there is a call to a given process, then the describeprocess request for this particular process is pushed at the top of the queue, so that the function is built rapidly and can execute.

**Comment by cehbrecht** [comment]
I faced this issue already in the command-line module. I'm using a lazy-load for `describeProcess` ... which unfortunately was a bit ugly with `click` ... but possible.

I know that pywps supports also the `describeProcess` with `identifier=all` to return all process with a single request:

http://localhost:5000/wps?service=WPS&version=1.0.0&request=DescribeProcess&identifier=all 

But I'm not sure if this is part of the standard, but it works with 52n:

http://geoprocessing.demo.52north.org:8080/wps/WebProcessingService?service=WPS&version=1.0.0&request=DescribeProcess&identifier=all

**Comment by cehbrecht** [comment]
... from Table 14 in the WPS 1.0.0 spec:

> The use of the Identifier ALL is restricted as an option for an Identifier in the DescribeProcess operation. When Identifier=ALL, the DescribeProcess operation shall return process descriptions for all processes served up by the WPS instance.

**Comment by cehbrecht** [comment]
... haven't checked if owslib.wps is prepared for this.

**Comment by huard** [comment]
Doesn't look like it.
