### ISSUE TITLE
Binder config and notebooks

### ISSUE THREAD

**Issue by huard** [bird-house/birdy#93]
## Description

Binder branch adds a working binder environment but all our notebooks assume there is a running emu server. 
Option 1: build and run emu inside the binder environment
Option 2: use a public URL for a live emu server.

**Comment by huard** [comment]
https://hub.mybinder.org/user/bird-house-birdy-xbprhoyx/notebooks/notebooks/emu-example.ipynb

**Comment by tomLandry** [comment]
Thank you for this David.

**Comment by huard** [comment]
@cehbrecht Preference ?

**Comment by cehbrecht** [comment]
@huard we might want to have binder just for user demo, not for development. So:

* having a demo notebook and environment which includes a released or latest birdy + what is needed for jupyter/binder.
* to make our life simpler, we can use a public service, like:
https://bovec.dkrz.de/ows/proxy/emu?Service=WPS&Request=GetCapabilities&Version=1.0.0
* maybe we want to have our own git repo for notebook demos?
https://github.com/cehbrecht/jupyterlab-notebooks

**Comment by huard** [comment]
Binder let's us specify a branch, so I guess we can point to a release tag. 

I'd like to set-up something rapidly for Tom's AGU presentation Wednesday. My suggestion would be to switch the URL from localhost to bovec in the binder branch and create a notebook corresponding to what is in the AGU presentation. I suggest that we keep the bird-house related notebooks in the birdhouse-docs repo.

**Comment by cehbrecht** [comment]
@huard go for it :) For the future we can still move things were we find it appropriate.
